//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.07 at 01:10:56 PM AEST 
//


package com.anz.cobolTransform.transform.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.anz.cobolTransform.transform.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PurchaseData_QNAME = new QName("", "PurchaseData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.anz.cobolTransform.transform.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PurchaseData }
     * 
     */
    public PurchaseData createPurchaseData() {
        return new PurchaseData();
    }

    /**
     * Create an instance of {@link PurchaseData.Invoice }
     * 
     */
    public PurchaseData.Invoice createPurchaseDataInvoice() {
        return new PurchaseData.Invoice();
    }

    /**
     * Create an instance of {@link PurchaseData.Invoice.Item }
     * 
     */
    public PurchaseData.Invoice.Item createPurchaseDataInvoiceItem() {
        return new PurchaseData.Invoice.Item();
    }

    /**
     * Create an instance of {@link PurchaseData.Invoice.Item.ItemGrocery }
     * 
     */
    public PurchaseData.Invoice.Item.ItemGrocery createPurchaseDataInvoiceItemItemGrocery() {
        return new PurchaseData.Invoice.Item.ItemGrocery();
    }

    /**
     * Create an instance of {@link PurchaseData.Invoice.Item.ItemNonGrocery }
     * 
     */
    public PurchaseData.Invoice.Item.ItemNonGrocery createPurchaseDataInvoiceItemItemNonGrocery() {
        return new PurchaseData.Invoice.Item.ItemNonGrocery();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PurchaseData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PurchaseData")
    public JAXBElement<PurchaseData> createPurchaseData(PurchaseData value) {
        return new JAXBElement<PurchaseData>(_PurchaseData_QNAME, PurchaseData.class, null, value);
    }

}
